POST http://localhost:8000/v1/auth/register
Content-Type: application/json

{
  "email": "yash.kukreja.98@gmail.com",
  "password":  "hello123",
  "name":  "Yashvardhan Kukreja",
  "address": "200 University Ave, Waterloo, Ontario",
  "date_of_birth":  "03/08/1998",
  "primary_role": "lender"
}
###
