######## Create
POST http://localhost:8000/v1/loan/request/
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwOGNmYWU0OC03NmVhLTQ0M2ItYjNjOC02MjRhZjRjOWUyMTEiLCJleHAiOjE3MTA1NDM4MjN9.vwrbbhUgkfa0eE-4JwUc7CFJTXinr8W0bs7akmOa2a0

{
"amount_start": 10000,
"amount_end": 20000,
"min_interest": 8,
"max_interest": 12,
"min_return_duration": 8640000,
"max_return_duration": 17280000,
"status": "available",
"description": "Sample description"
}

#{
#  "meta": {
#    "message": "Loan Request created successfully"
#  },
#  "payload": {
#    "loan_request": {
#      "uuid": "2fec6411-1486-47ca-88ab-2c311f22ed42",
#      "user_uuid": "08cfae48-76ea-443b-b3c8-624af4c9e211",
#      "amount_start": 10000,
#      "amount_end": 20000,
#      "min_interest": 8,
#      "max_interest": 12,
#      "status": "available",
#      "description": "Sample description"
#    }
#  }
#}


######## Update
PUT http://localhost:8000/v1/loan/request/foo-bar-uuid
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwOGNmYWU0OC03NmVhLTQ0M2ItYjNjOC02MjRhZjRjOWUyMTEiLCJleHAiOjE3MTA1NDM4MjN9.vwrbbhUgkfa0eE-4JwUc7CFJTXinr8W0bs7akmOa2a0

{
"max_interest": 14
}

#{
#  "meta": {
#    "message": "Loan request updated successfully"
#  },
#  "payload": {
#    "loan_request": {
#      "uuid": "2fec6411-1486-47ca-88ab-2c311f22ed42",
#      "user_uuid": "08cfae48-76ea-443b-b3c8-624af4c9e211",
#      "amount_start": 10000,
#      "amount_end": 20000,
#      "min_interest": 8,
#      "max_interest": 14,
#      "status": "available",
#      "description": "Sample description"
#    }
#  }
#}


### Failure
#{
#  "meta": {
#    "message": "failed to update the loan request: failed to find the loan request corresponding to the provided loan request uuid: loan request not found"
#  }
#}

######## Get by user
GET http://localhost:8000/v1/loan/request/
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwOGNmYWU0OC03NmVhLTQ0M2ItYjNjOC02MjRhZjRjOWUyMTEiLCJleHAiOjE3MTA1NDM4MjN9.vwrbbhUgkfa0eE-4JwUc7CFJTXinr8W0bs7akmOa2a0

#{
#  "meta": {
#    "message": "Your loan Request fetched successfully"
#  },
#  "payload": {
#    "loan_requests": [
#      {
#        "uuid": "2fec6411-1486-47ca-88ab-2c311f22ed42",
#        "user_uuid": "08cfae48-76ea-443b-b3c8-624af4c9e211",
#        "amount_start": 10000,
#        "amount_end": 20000,
#        "min_interest": 8,
#        "max_interest": 14,
#        "status": "available",
#        "description": "Sample description"
#      }
#    ]
#  }
#}


######## Get all loan requests
GET http://localhost:8000/v1/loan/request/loan-requests
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwOGNmYWU0OC03NmVhLTQ0M2ItYjNjOC02MjRhZjRjOWUyMTEiLCJleHAiOjE3MTA1NDM4MjN9.vwrbbhUgkfa0eE-4JwUc7CFJTXinr8W0bs7akmOa2a0

#{
#  "meta": {
#    "message": "Loan requests fetched successfully"
#  },
#  "payload": {
#    "loan_requests": [
#      {
#        "uuid": "2fec6411-1486-47ca-88ab-2c311f22ed42",
#        "user_uuid": "08cfae48-76ea-443b-b3c8-624af4c9e211",
#        "amount_start": 10000,
#        "amount_end": 20000,
#        "min_interest": 8,
#        "max_interest": 14,
#        "status": "available",
#        "description": "Sample description"
#      },
#      {
#        "uuid": "df72e1b6-bbc6-4366-bd94-8b304da69ff2",
#        "user_uuid": "08cfae48-76ea-443b-b3c8-624af4c9e211",
#        "amount_start": 10000,
#        "amount_end": 20000,
#        "min_interest": 10,
#        "max_interest": 14,
#        "status": "available",
#        "description": "Sample description"
#      }
#    ]
#  }
#}
#

##### DELETE
DELETE http://localhost:8000/v1/loan/proposals/foo-bar-id
Accept: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwOGNmYWU0OC03NmVhLTQ0M2ItYjNjOC02MjRhZjRjOWUyMTEiLCJleHAiOjE3MTA1NDM4MjN9.vwrbbhUgkfa0eE-4JwUc7CFJTXinr8W0bs7akmOa2a0

#{
#  "meta": {
#    "message": "Loan request deleted successfully"
#  }
#}