image: golang:1.22.0
pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          
          script:
            - echo "Deployment Starting"
            - scp -o StrictHostKeyChecking=no ./deploy.sh ubuntu@ec2-3-15-22-52.us-east-2.compute.amazonaws.com:/tmp/deploy.sh
            - ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-15-22-52.us-east-2.compute.amazonaws.com "DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD DB_HOST=$DB_HOST DB_PORT=$DB_PORT bash /tmp/deploy.sh"
            - echo "Deploying finished"