image: golang:1.22.0
pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          
          script:
            - echo "Deployment Starting"
            - cat ./deploy.sh | ssh -tt -o StrictHostKeyChecking=no ubuntu@ec2-3-15-22-52.us-east-2.compute.amazonaws.com
            - echo "Deploying finished"