image: golang:1.22.0
pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          
          script:
            - echo "Deployment Starting"
            - ./deploy.sh 
            - echo "Deploying finished"