image: golang:1.22.0
pipelines:
  default:
      - step:
          name: Deploy to test
          deployment: test
          
          script:
            - echo "Deployment Starting"
            - scp -o StrictHostKeyChecking=no ./deploy.sh ubuntu@ec2-3-15-22-52.us-east-2.compute.amazonaws.com:/tmp/deploy.sh
            - ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-15-22-52.us-east-2.compute.amazonaws.com 'bash /tmp/deploy.sh'
            - echo "Deploying finished"